name: hero_cards
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^5.2.1
  cloud_firestore: ^4.13.2
  dio: ^5.3.4
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  go_router: ^12.1.1
  loading_animation_widget: ^1.2.0+4
  local_auth: ^2.1.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: 'Horizon'
      fonts:
      - asset: assets/fonts/Horizon.ttf
  assets:
    - .env    
    - assets/images/
    - assets/sounds/
